### ISSUE TITLE
SASL incompatability

### ISSUE THREAD

**Issue by martindurant** [conda-forge/libhdfs3-feedstock#12]
It turns out that hdfs3 can connect to a kerb hdfs with a libgsasl 1.8.0-0 in the anaconda channel but *not* with libgsasl 1.8.0-0 in conda-forge. Since (lib)hdfs3 is usually installed with `-c conda-forge`, this has caused some of the reports of 
```
ConnectionError: Connection Failed: HdfsRpcException: Failed to invoke RPC call "getFsStats" on server "ip-172-31-22-117:8020"	Caused by: HdfsIOException: Cannot initialize client (2): Unknown SASL mechanism
```

cc @koverholt 
xref https://github.com/dask/hdfs3/issues/91

**Comment by martindurant** [comment]
^ cc @quasiben

**Comment by quasiben** [comment]
I believe the recipes are identical.  Not sure what would cause the issue here

**Comment by kpweiler** [comment]
According to this:

https://github.com/conda-forge/libgsasl-feedstock/blob/master/recipe/build.sh

`--with-gssapi-impl=mit` is specified and therefore should work.

However, I have verified that installing libgsasl from the anaconda channel instead of conda-forge allows me to connect.
