### ISSUE TITLE
Update libhdfs3 conda recipe to new HAWQ repo

### ISSUE THREAD

**Issue by koverholt** [conda-forge/libhdfs3-feedstock#3]
The `libhdfs3` source has moved to the Apache HAWQ repo. Need to update the conda recipe accordingly to point to: https://github.com/apache/incubator-hawq/tree/master/depends/libhdfs3.

However, this is currently blocked as there isn't a clean way to get a specific version of `libhdfs3` since it's part of the larger HAWQ repo.

**Comment by koverholt** [comment]
I posted to the [HAWQ mailing list](http://mail-archives.apache.org/mod_mbox/hawq-dev/201605.mbox/%3CCAGEDv1YeBEXWxOpv6Y-St=rtVD=Xcf5CzeuMMb-tMQn4C4gB7Q@mail.gmail.com%3E) asking how we can track libhdfs3 versions from the new [HAWQ repo](https://github.com/apache/incubator-hawq), but there is not a clean way to do this at the moment.

**Comment by koverholt** [comment]
Related issue: https://issues.apache.org/jira/browse/HAWQ-1046

**Comment by koverholt** [comment]
More discussion here: http://mail-archives.apache.org/mod_mbox/hawq-dev/201609.mbox/%3CCA+ULb+u+7k7fbGz1bmNAyATUfUrY-Lj8-BoSKD4RJAFOoZYzaw@mail.gmail.com%3E

**Comment by koverholt** [comment]
Issues related to separate release tarball for libhdfs3 (https://issues.apache.org/jira/browse/HAWQ-1058) and a separate libhdfs3 repository (https://issues.apache.org/jira/browse/HAWQ-1059).

**Comment by kpweiler** [comment]
Is this repository maybe the correct one?

https://github.com/apache/incubator-hawq/tree/master/depends/libhdfs3

or this?

git://git.apache.org/incubator-hawq.git

**Comment by martindurant** [comment]
Yes, plus others like https://github.com/bdrosen96/libhdfs3
Hopefully we can combine these into something useful.
