### ISSUE TITLE
libgcrypt-11 missing

### ISSUE THREAD

**Issue by mrocklin** [conda-forge/libhdfs3-feedstock#4]
This library depends on an external library, libgcrypt-11.  At least on Ubuntu 16.04 this shared library is missing, and worse, is not easy to get from the system package manager (which instead prefers libgcrypt-20).

**Comment by mrocklin** [comment]
Resolvable by 

```
conda install -c clinicalgraphics libgcrypt11
```

**Comment by koverholt** [comment]
I was not able to reproduce this issue.

I ran `conda install hdfs3 -c conda-forge` on a fresh Ubuntu 16.04 instance (`ami-29f96d3e` on `us-east-1` on Amazon EC2) and was able to import and connect to HDFS without any errors even though I only have libgcrypt-20 installed:

```
$ locate libgcrypt
/lib/x86_64-linux-gnu/libgcrypt.so.20
/lib/x86_64-linux-gnu/libgcrypt.so.20.0.5
/usr/share/doc/libgcrypt20
/usr/share/doc/libgcrypt20/AUTHORS.gz
/usr/share/doc/libgcrypt20/NEWS.gz
/usr/share/doc/libgcrypt20/README.gz
/usr/share/doc/libgcrypt20/THANKS.gz
/usr/share/doc/libgcrypt20/changelog.Debian.gz
/usr/share/doc/libgcrypt20/copyright
/var/lib/dpkg/info/libgcrypt20:amd64.list
/var/lib/dpkg/info/libgcrypt20:amd64.md5sums
/var/lib/dpkg/info/libgcrypt20:amd64.shlibs
/var/lib/dpkg/info/libgcrypt20:amd64.symbols
/var/lib/dpkg/info/libgcrypt20:amd64.triggers
```

Output:

```
In [1]: import hdfs3

In [2]: hdfs3.HDFileSystem()
Out[2]: hdfs://localhost:8020, Connected
```

**Comment by koverholt** [comment]
This should be solved in the latest `libhdfs3` conda package that was built from https://github.com/conda-forge/libhdfs3-feedstock/pull/6 with the latest available versions of `protobuf` and `boost`.

I tested `conda install hdfs3 -c conda-forge` on Ubuntu 14.04/16.04 and CentOS 6/7 and things are working for me without the need for `libgcrypt-11`.

Please reopen if you continue to have issues.

**Comment by GoingMyWay** [comment]
> Resolvable by
> 
> ```
> conda install -c clinicalgraphics libgcrypt11
> ```

Hi, it seems the repo is not available

```
Collecting package metadata (current_repodata.json): failed

UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: clinicalgraphics
  channel url: https://conda.anaconda.org/clinicalgraphics
  error code: 404

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.
```
