### ISSUE TITLE
Missing dependency on openssl

### ISSUE THREAD

**Issue by ypsah** [conda-forge/libhdfs3-feedstock#42]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: libhdfs3 is missing a dependency on openssl

Reproducer:

In a fresh/empty conda environment, install `conda-forge`'s`libhdfs3` library:

```bash
conda install -c conda-forge libhdfs3
```

Then check the libraries which it is linked against:

```console
$ ldd path/to/conda/env/lib/libhdfs3.so
(...)
libcrypto.so.3 => ...
```

(`libcrypto.so.<x>` is provided by `openssl=<x>`)

But `libhdfs3` itself does not require `openssl=<x>`. It gets installed as a dependency of `krb5`, and with the version constraints on `krb5`, we can end up installing alternatively `openssl 1.1` or `openssl 3.0`.

With the latest build of `libhdfs3`, only `openssl 3.0` will work. But since the dependency is not explicit, `conda` doesn't know about it.

For now, I had to pin the version of libhdfs3 to the last `openssl 1.1`-compatible build, and pin openssl to `1.1` manually.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /opt/conda/envs/test
#
# Name                    Version                   Build  Channel
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : test
    active env location : /opt/conda/envs/test
            shell level : 2
       user config file : /work/.condarc
 populated config files :
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.9.5.final.0
       virtual packages : __linux=3.10.0=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/conda (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
https://repo.anaconda.com/pkgs/main/noarch
https://repo.anaconda.com/pkgs/r/linux-64
https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /work/.conda/pkgs
       envs directories : /opt/conda/envs
                          /work/.conda/envs
               platform : linux-64
             user-agent : conda/4.11.0 requests/2.25.1 CPython/3.9.5
Linux/3.10.0-1160.49.1.el7.x86_64 centos/7.6.1810 glibc/2.17
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```
</details>

**Comment by xhochy** [comment]
Can you send a PR, please?
